/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CardImage = {
  asset?: SanityImageAssetReference;
  media?: unknown // Unable to locate the referenced type "cardImage.media" in schema
;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type Youtube = {
  _type: "youtube";
  label?: string;
  id?: string;
};

export type PageSlug = {
  _type: "pageSlug";
  slug?: Slug;
};

export type MailchimpForm = {
  _type: "mailchimpForm";
  note?: string;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type EventsPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "eventsPage";
};

export type Link = {
  _type: "link";
  linkType?: "internal" | "external";
  page?: PageReference | ProjectReference | EventsPageReference;
  external?: string;
  anchor?: Slug;
};

export type FeatureCardsBlock = {
  _type: "featureCardsBlock";
  heading?: string;
  cards?: Array<{
    title?: string;
    description?: string;
    cardImage?: CardImage;
    link?: Link;
    _type: "card";
    _key: string;
  }>;
  background?: "light" | "dark";
};

export type TextBlock = {
  _type: "textBlock";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
  } & Youtube | {
    _key: string;
  } & MailchimpForm>;
  featureImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imageAlign?: "left" | "right";
  textAlign?: "left" | "center" | "justify";
  leadInText?: boolean;
  sectionId?: string;
  cta?: string;
  ctaLink?: Link;
};

export type PageBuilder = Array<{
  _key: string;
} & HeroBlock | {
  _key: string;
} & TextBlock | {
  _key: string;
} & FeatureCardsBlock>;

export type HeroBlock = {
  _type: "heroBlock";
  heading?: string;
  subtitle?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  size?: "small" | "large";
};

export type EventItem = {
  _id: string;
  _type: "eventItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  eventDatetime?: string;
  location?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type EventsPage = {
  _id: string;
  _type: "eventsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageSlug?: PageSlug;
  pageBuilder?: PageBuilder;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageSlug?: PageSlug;
  pageBuilder?: PageBuilder;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageSlug?: PageSlug;
  pageBuilder?: PageBuilder;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  siteTagline?: string;
  mainNav?: Array<{
    label?: string;
    link?: Link;
    _type: "navLink";
    _key: string;
  }>;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageBuilder?: PageBuilder;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SanityImageAssetReference | CardImage | Youtube | PageSlug | MailchimpForm | PageReference | ProjectReference | EventsPageReference | Link | FeatureCardsBlock | TextBlock | PageBuilder | HeroBlock | EventItem | EventsPage | Project | Page | Slug | SiteSettings | Homepage | SanityImageCrop | SanityImageHotspot | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../website/src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings" && defined(siteName)][0]{  siteName,  siteTagline,  "mainNav": coalesce(mainNav[defined(label)] {    "label": coalesce(label, ""),    "link": link {   linkType,  linkType == 'internal' => {    "page": page-> {      _type,      "slug": pageSlug.slug.current,    },    "anchor": anchor.current,    "url": null,  },  linkType == 'external' => {    "page": null,    "anchor": null,    "url": external,  } }  }, [])}
export type SITE_SETTINGS_QUERY_RESULT = {
  siteName: string;
  siteTagline: string | null;
  mainNav: Array<{
    label: string;
    link: {
      linkType: "external" | "internal" | null;
      page: null;
      anchor: null;
      url: string | null;
    } | {
      linkType: "external" | "internal" | null;
      page: {
        _type: "eventsPage";
        slug: string | null;
      } | {
        _type: "page";
        slug: string | null;
      } | {
        _type: "project";
        slug: string | null;
      } | null;
      anchor: string | null;
      url: null;
    } | {
      linkType: "external" | "internal" | null;
    } | null;
  }> | Array<never>;
} | null;

// Source: ../website/src/sanity/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_id == "home"][0]{    pageBuilder[] {    _key, _type,      _type == "heroBlock" => {    heading,    subtitle,    size,    backgroundImage {   asset->{    _id,    _type,    url,    metadata { lqip, dimensions { width, height } }  },  crop,  hotspot,  alt,  "dominantColor": asset->metadata.palette.dominant.background },  },      _type == "textBlock" => {    content,    cta,    "ctaLink": ctaLink {   linkType,  linkType == 'internal' => {    "page": page-> {      _type,      "slug": pageSlug.slug.current,    },    "anchor": anchor.current,    "url": null,  },  linkType == 'external' => {    "page": null,    "anchor": null,    "url": external,  } },    textAlign,    leadInText,    featureImage {   asset->{    _id,    _type,    url,    metadata { lqip, dimensions { width, height } }  },  crop,  hotspot,  alt,  "dominantColor": asset->metadata.palette.dominant.background },    imageAlign,    sectionId  },      _type == "featureCardsBlock" => {    heading,    background,     cards[] {      title,      description,      cardImage {   asset->{    _id,    _type,    url,    metadata { lqip, dimensions { width, height } }  },  crop,  hotspot,  alt,  "dominantColor": asset->metadata.palette.dominant.background },      "link": link {   linkType,  linkType == 'internal' => {    "page": page-> {      _type,      "slug": pageSlug.slug.current,    },    "anchor": anchor.current,    "url": null,  },  linkType == 'external' => {    "page": null,    "anchor": null,    "url": external,  } }    }  }  },}
export type HOMEPAGE_QUERY_RESULT = {
  pageBuilder: null;
} | {
  pageBuilder: Array<{
    _key: string;
    _type: "featureCardsBlock";
    heading: string | null;
    background: "dark" | "light" | null;
    cards: Array<{
      title: string | null;
      description: string | null;
      cardImage: {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        alt: string | null;
        dominantColor: string | null;
      } | null;
      link: {
        linkType: "external" | "internal" | null;
        page: null;
        anchor: null;
        url: string | null;
      } | {
        linkType: "external" | "internal" | null;
        page: {
          _type: "eventsPage";
          slug: string | null;
        } | {
          _type: "page";
          slug: string | null;
        } | {
          _type: "project";
          slug: string | null;
        } | null;
        anchor: string | null;
        url: null;
      } | {
        linkType: "external" | "internal" | null;
      } | null;
    }> | null;
  } | {
    _key: string;
    _type: "heroBlock";
    heading: string | null;
    subtitle: string | null;
    size: "large" | "small" | null;
    backgroundImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
  } | {
    _key: string;
    _type: "textBlock";
    content: Array<{
      _key: string;
    } & MailchimpForm | {
      _key: string;
    } & Youtube | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    cta: string | null;
    ctaLink: {
      linkType: "external" | "internal" | null;
      page: null;
      anchor: null;
      url: string | null;
    } | {
      linkType: "external" | "internal" | null;
      page: {
        _type: "eventsPage";
        slug: string | null;
      } | {
        _type: "page";
        slug: string | null;
      } | {
        _type: "project";
        slug: string | null;
      } | null;
      anchor: string | null;
      url: null;
    } | {
      linkType: "external" | "internal" | null;
    } | null;
    textAlign: "center" | "justify" | "left" | null;
    leadInText: boolean | null;
    featureImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
    imageAlign: "left" | "right" | null;
    sectionId: string | null;
  }> | null;
} | null;

// Source: ../website/src/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && defined(pageSlug.slug.current)] {  _type,  title,      "slug": select(      defined(pageSlug.parent) => pageSlug.parent->pageSlug.slug.current + "/" + pageSlug.slug.current,      pageSlug.slug.current    )  ,    pageBuilder[] {    _key, _type,      _type == "heroBlock" => {    heading,    subtitle,    size,    backgroundImage {   asset->{    _id,    _type,    url,    metadata { lqip, dimensions { width, height } }  },  crop,  hotspot,  alt,  "dominantColor": asset->metadata.palette.dominant.background },  },      _type == "textBlock" => {    content,    cta,    "ctaLink": ctaLink {   linkType,  linkType == 'internal' => {    "page": page-> {      _type,      "slug": pageSlug.slug.current,    },    "anchor": anchor.current,    "url": null,  },  linkType == 'external' => {    "page": null,    "anchor": null,    "url": external,  } },    textAlign,    leadInText,    featureImage {   asset->{    _id,    _type,    url,    metadata { lqip, dimensions { width, height } }  },  crop,  hotspot,  alt,  "dominantColor": asset->metadata.palette.dominant.background },    imageAlign,    sectionId  },      _type == "featureCardsBlock" => {    heading,    background,     cards[] {      title,      description,      cardImage {   asset->{    _id,    _type,    url,    metadata { lqip, dimensions { width, height } }  },  crop,  hotspot,  alt,  "dominantColor": asset->metadata.palette.dominant.background },      "link": link {   linkType,  linkType == 'internal' => {    "page": page-> {      _type,      "slug": pageSlug.slug.current,    },    "anchor": anchor.current,    "url": null,  },  linkType == 'external' => {    "page": null,    "anchor": null,    "url": external,  } }    }  }  }}
export type PAGE_QUERY_RESULT = Array<{
  _type: "page";
  title: string | null;
  slug: string | null;
  pageBuilder: Array<{
    _key: string;
    _type: "featureCardsBlock";
    heading: string | null;
    background: "dark" | "light" | null;
    cards: Array<{
      title: string | null;
      description: string | null;
      cardImage: {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        alt: string | null;
        dominantColor: string | null;
      } | null;
      link: {
        linkType: "external" | "internal" | null;
        page: null;
        anchor: null;
        url: string | null;
      } | {
        linkType: "external" | "internal" | null;
        page: {
          _type: "eventsPage";
          slug: string | null;
        } | {
          _type: "page";
          slug: string | null;
        } | {
          _type: "project";
          slug: string | null;
        } | null;
        anchor: string | null;
        url: null;
      } | {
        linkType: "external" | "internal" | null;
      } | null;
    }> | null;
  } | {
    _key: string;
    _type: "heroBlock";
    heading: string | null;
    subtitle: string | null;
    size: "large" | "small" | null;
    backgroundImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
  } | {
    _key: string;
    _type: "textBlock";
    content: Array<{
      _key: string;
    } & MailchimpForm | {
      _key: string;
    } & Youtube | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    cta: string | null;
    ctaLink: {
      linkType: "external" | "internal" | null;
      page: null;
      anchor: null;
      url: string | null;
    } | {
      linkType: "external" | "internal" | null;
      page: {
        _type: "eventsPage";
        slug: string | null;
      } | {
        _type: "page";
        slug: string | null;
      } | {
        _type: "project";
        slug: string | null;
      } | null;
      anchor: string | null;
      url: null;
    } | {
      linkType: "external" | "internal" | null;
    } | null;
    textAlign: "center" | "justify" | "left" | null;
    leadInText: boolean | null;
    featureImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
    imageAlign: "left" | "right" | null;
    sectionId: string | null;
  }> | null;
}>;

// Source: ../website/src/sanity/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && defined(pageSlug.slug.current)] {  _type,  title,      "slug": select(      defined(pageSlug.parent) => pageSlug.parent->pageSlug.slug.current + "/" + pageSlug.slug.current,      pageSlug.slug.current    )  ,    pageBuilder[] {    _key, _type,      _type == "heroBlock" => {    heading,    subtitle,    size,    backgroundImage {   asset->{    _id,    _type,    url,    metadata { lqip, dimensions { width, height } }  },  crop,  hotspot,  alt,  "dominantColor": asset->metadata.palette.dominant.background },  },      _type == "textBlock" => {    content,    cta,    "ctaLink": ctaLink {   linkType,  linkType == 'internal' => {    "page": page-> {      _type,      "slug": pageSlug.slug.current,    },    "anchor": anchor.current,    "url": null,  },  linkType == 'external' => {    "page": null,    "anchor": null,    "url": external,  } },    textAlign,    leadInText,    featureImage {   asset->{    _id,    _type,    url,    metadata { lqip, dimensions { width, height } }  },  crop,  hotspot,  alt,  "dominantColor": asset->metadata.palette.dominant.background },    imageAlign,    sectionId  },      _type == "featureCardsBlock" => {    heading,    background,     cards[] {      title,      description,      cardImage {   asset->{    _id,    _type,    url,    metadata { lqip, dimensions { width, height } }  },  crop,  hotspot,  alt,  "dominantColor": asset->metadata.palette.dominant.background },      "link": link {   linkType,  linkType == 'internal' => {    "page": page-> {      _type,      "slug": pageSlug.slug.current,    },    "anchor": anchor.current,    "url": null,  },  linkType == 'external' => {    "page": null,    "anchor": null,    "url": external,  } }    }  }  }}
export type PROJECT_QUERY_RESULT = Array<{
  _type: "project";
  title: string | null;
  slug: string | null;
  pageBuilder: Array<{
    _key: string;
    _type: "featureCardsBlock";
    heading: string | null;
    background: "dark" | "light" | null;
    cards: Array<{
      title: string | null;
      description: string | null;
      cardImage: {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        alt: string | null;
        dominantColor: string | null;
      } | null;
      link: {
        linkType: "external" | "internal" | null;
        page: null;
        anchor: null;
        url: string | null;
      } | {
        linkType: "external" | "internal" | null;
        page: {
          _type: "eventsPage";
          slug: string | null;
        } | {
          _type: "page";
          slug: string | null;
        } | {
          _type: "project";
          slug: string | null;
        } | null;
        anchor: string | null;
        url: null;
      } | {
        linkType: "external" | "internal" | null;
      } | null;
    }> | null;
  } | {
    _key: string;
    _type: "heroBlock";
    heading: string | null;
    subtitle: string | null;
    size: "large" | "small" | null;
    backgroundImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
  } | {
    _key: string;
    _type: "textBlock";
    content: Array<{
      _key: string;
    } & MailchimpForm | {
      _key: string;
    } & Youtube | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    cta: string | null;
    ctaLink: {
      linkType: "external" | "internal" | null;
      page: null;
      anchor: null;
      url: string | null;
    } | {
      linkType: "external" | "internal" | null;
      page: {
        _type: "eventsPage";
        slug: string | null;
      } | {
        _type: "page";
        slug: string | null;
      } | {
        _type: "project";
        slug: string | null;
      } | null;
      anchor: string | null;
      url: null;
    } | {
      linkType: "external" | "internal" | null;
    } | null;
    textAlign: "center" | "justify" | "left" | null;
    leadInText: boolean | null;
    featureImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
    imageAlign: "left" | "right" | null;
    sectionId: string | null;
  }> | null;
}>;

// Source: ../website/src/sanity/queries.ts
// Variable: EVENTS_PAGE_QUERY
// Query: *[_id == "eventsPage"][0]{  _type,  title,    pageBuilder[] {    _key, _type,      _type == "heroBlock" => {    heading,    subtitle,    size,    backgroundImage {   asset->{    _id,    _type,    url,    metadata { lqip, dimensions { width, height } }  },  crop,  hotspot,  alt,  "dominantColor": asset->metadata.palette.dominant.background },  },      _type == "textBlock" => {    content,    cta,    "ctaLink": ctaLink {   linkType,  linkType == 'internal' => {    "page": page-> {      _type,      "slug": pageSlug.slug.current,    },    "anchor": anchor.current,    "url": null,  },  linkType == 'external' => {    "page": null,    "anchor": null,    "url": external,  } },    textAlign,    leadInText,    featureImage {   asset->{    _id,    _type,    url,    metadata { lqip, dimensions { width, height } }  },  crop,  hotspot,  alt,  "dominantColor": asset->metadata.palette.dominant.background },    imageAlign,    sectionId  },      _type == "featureCardsBlock" => {    heading,    background,     cards[] {      title,      description,      cardImage {   asset->{    _id,    _type,    url,    metadata { lqip, dimensions { width, height } }  },  crop,  hotspot,  alt,  "dominantColor": asset->metadata.palette.dominant.background },      "link": link {   linkType,  linkType == 'internal' => {    "page": page-> {      _type,      "slug": pageSlug.slug.current,    },    "anchor": anchor.current,    "url": null,  },  linkType == 'external' => {    "page": null,    "anchor": null,    "url": external,  } }    }  }  },}
export type EVENTS_PAGE_QUERY_RESULT = {
  _type: "eventItem";
  title: string | null;
  pageBuilder: null;
} | {
  _type: "eventsPage";
  title: string | null;
  pageBuilder: Array<{
    _key: string;
    _type: "featureCardsBlock";
    heading: string | null;
    background: "dark" | "light" | null;
    cards: Array<{
      title: string | null;
      description: string | null;
      cardImage: {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        alt: string | null;
        dominantColor: string | null;
      } | null;
      link: {
        linkType: "external" | "internal" | null;
        page: null;
        anchor: null;
        url: string | null;
      } | {
        linkType: "external" | "internal" | null;
        page: {
          _type: "eventsPage";
          slug: string | null;
        } | {
          _type: "page";
          slug: string | null;
        } | {
          _type: "project";
          slug: string | null;
        } | null;
        anchor: string | null;
        url: null;
      } | {
        linkType: "external" | "internal" | null;
      } | null;
    }> | null;
  } | {
    _key: string;
    _type: "heroBlock";
    heading: string | null;
    subtitle: string | null;
    size: "large" | "small" | null;
    backgroundImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
  } | {
    _key: string;
    _type: "textBlock";
    content: Array<{
      _key: string;
    } & MailchimpForm | {
      _key: string;
    } & Youtube | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    cta: string | null;
    ctaLink: {
      linkType: "external" | "internal" | null;
      page: null;
      anchor: null;
      url: string | null;
    } | {
      linkType: "external" | "internal" | null;
      page: {
        _type: "eventsPage";
        slug: string | null;
      } | {
        _type: "page";
        slug: string | null;
      } | {
        _type: "project";
        slug: string | null;
      } | null;
      anchor: string | null;
      url: null;
    } | {
      linkType: "external" | "internal" | null;
    } | null;
    textAlign: "center" | "justify" | "left" | null;
    leadInText: boolean | null;
    featureImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
    imageAlign: "left" | "right" | null;
    sectionId: string | null;
  }> | null;
} | {
  _type: "homepage";
  title: string | null;
  pageBuilder: Array<{
    _key: string;
    _type: "featureCardsBlock";
    heading: string | null;
    background: "dark" | "light" | null;
    cards: Array<{
      title: string | null;
      description: string | null;
      cardImage: {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        alt: string | null;
        dominantColor: string | null;
      } | null;
      link: {
        linkType: "external" | "internal" | null;
        page: null;
        anchor: null;
        url: string | null;
      } | {
        linkType: "external" | "internal" | null;
        page: {
          _type: "eventsPage";
          slug: string | null;
        } | {
          _type: "page";
          slug: string | null;
        } | {
          _type: "project";
          slug: string | null;
        } | null;
        anchor: string | null;
        url: null;
      } | {
        linkType: "external" | "internal" | null;
      } | null;
    }> | null;
  } | {
    _key: string;
    _type: "heroBlock";
    heading: string | null;
    subtitle: string | null;
    size: "large" | "small" | null;
    backgroundImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
  } | {
    _key: string;
    _type: "textBlock";
    content: Array<{
      _key: string;
    } & MailchimpForm | {
      _key: string;
    } & Youtube | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    cta: string | null;
    ctaLink: {
      linkType: "external" | "internal" | null;
      page: null;
      anchor: null;
      url: string | null;
    } | {
      linkType: "external" | "internal" | null;
      page: {
        _type: "eventsPage";
        slug: string | null;
      } | {
        _type: "page";
        slug: string | null;
      } | {
        _type: "project";
        slug: string | null;
      } | null;
      anchor: string | null;
      url: null;
    } | {
      linkType: "external" | "internal" | null;
    } | null;
    textAlign: "center" | "justify" | "left" | null;
    leadInText: boolean | null;
    featureImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
    imageAlign: "left" | "right" | null;
    sectionId: string | null;
  }> | null;
} | {
  _type: "page";
  title: string | null;
  pageBuilder: Array<{
    _key: string;
    _type: "featureCardsBlock";
    heading: string | null;
    background: "dark" | "light" | null;
    cards: Array<{
      title: string | null;
      description: string | null;
      cardImage: {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        alt: string | null;
        dominantColor: string | null;
      } | null;
      link: {
        linkType: "external" | "internal" | null;
        page: null;
        anchor: null;
        url: string | null;
      } | {
        linkType: "external" | "internal" | null;
        page: {
          _type: "eventsPage";
          slug: string | null;
        } | {
          _type: "page";
          slug: string | null;
        } | {
          _type: "project";
          slug: string | null;
        } | null;
        anchor: string | null;
        url: null;
      } | {
        linkType: "external" | "internal" | null;
      } | null;
    }> | null;
  } | {
    _key: string;
    _type: "heroBlock";
    heading: string | null;
    subtitle: string | null;
    size: "large" | "small" | null;
    backgroundImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
  } | {
    _key: string;
    _type: "textBlock";
    content: Array<{
      _key: string;
    } & MailchimpForm | {
      _key: string;
    } & Youtube | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    cta: string | null;
    ctaLink: {
      linkType: "external" | "internal" | null;
      page: null;
      anchor: null;
      url: string | null;
    } | {
      linkType: "external" | "internal" | null;
      page: {
        _type: "eventsPage";
        slug: string | null;
      } | {
        _type: "page";
        slug: string | null;
      } | {
        _type: "project";
        slug: string | null;
      } | null;
      anchor: string | null;
      url: null;
    } | {
      linkType: "external" | "internal" | null;
    } | null;
    textAlign: "center" | "justify" | "left" | null;
    leadInText: boolean | null;
    featureImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
    imageAlign: "left" | "right" | null;
    sectionId: string | null;
  }> | null;
} | {
  _type: "project";
  title: string | null;
  pageBuilder: Array<{
    _key: string;
    _type: "featureCardsBlock";
    heading: string | null;
    background: "dark" | "light" | null;
    cards: Array<{
      title: string | null;
      description: string | null;
      cardImage: {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number | null;
              height: number | null;
            } | null;
          } | null;
        } | null;
        crop: SanityImageCrop | null;
        hotspot: SanityImageHotspot | null;
        alt: string | null;
        dominantColor: string | null;
      } | null;
      link: {
        linkType: "external" | "internal" | null;
        page: null;
        anchor: null;
        url: string | null;
      } | {
        linkType: "external" | "internal" | null;
        page: {
          _type: "eventsPage";
          slug: string | null;
        } | {
          _type: "page";
          slug: string | null;
        } | {
          _type: "project";
          slug: string | null;
        } | null;
        anchor: string | null;
        url: null;
      } | {
        linkType: "external" | "internal" | null;
      } | null;
    }> | null;
  } | {
    _key: string;
    _type: "heroBlock";
    heading: string | null;
    subtitle: string | null;
    size: "large" | "small" | null;
    backgroundImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
  } | {
    _key: string;
    _type: "textBlock";
    content: Array<{
      _key: string;
    } & MailchimpForm | {
      _key: string;
    } & Youtube | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "h3" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    cta: string | null;
    ctaLink: {
      linkType: "external" | "internal" | null;
      page: null;
      anchor: null;
      url: string | null;
    } | {
      linkType: "external" | "internal" | null;
      page: {
        _type: "eventsPage";
        slug: string | null;
      } | {
        _type: "page";
        slug: string | null;
      } | {
        _type: "project";
        slug: string | null;
      } | null;
      anchor: string | null;
      url: null;
    } | {
      linkType: "external" | "internal" | null;
    } | null;
    textAlign: "center" | "justify" | "left" | null;
    leadInText: boolean | null;
    featureImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number | null;
            height: number | null;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
      dominantColor: string | null;
    } | null;
    imageAlign: "left" | "right" | null;
    sectionId: string | null;
  }> | null;
} | {
  _type: "sanity.fileAsset";
  title: string | null;
  pageBuilder: null;
} | {
  _type: "sanity.imageAsset";
  title: string | null;
  pageBuilder: null;
} | {
  _type: "siteSettings";
  title: null;
  pageBuilder: null;
} | null;

// Source: ../website/src/sanity/queries.ts
// Variable: EVENT_ITEMS_QUERY
// Query: *[_type == "eventItem"] | order(eventDatetime desc) {  _type,  title,  eventDatetime,  location,  description}
export type EVENT_ITEMS_QUERY_RESULT = Array<{
  _type: "eventItem";
  title: string | null;
  eventDatetime: string | null;
  location: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
}>;

